spring.application.name=raspi-health-service
server.port=8181


healthcheck.apps[0].name=app-one
healthcheck.apps[0].systemd-unit=app-one.service
healthcheck.apps[1].name=app-two
healthcheck.apps[1].systemd-unit=app-two.service