spring.application.name=raspi-health-service
server.port=8181


healthcheck.apps[0].name=Finance
healthcheck.apps[0].systemd-unit=finance-backend.service
healthcheck.apps[1].name=Rent-AMLI
healthcheck.apps[1].systemd-unit=rent-scraper-backend.service